### ISSUE TITLE
lamahice attributes lat/lon values

### ISSUE THREAD

**Issue by fmclerc** [kratzert/Caravan#28]
Hi everyone!
Thanks a lot to all of you who contributed to the Caravan dataset and made it so large and helpful for large-sample studies!
I just realized that in the attributes_other_lamahice file, the latitude and longitude values seem to be switched.
I hope that this is the right place to address this issue.
Best wishes, Franziska

**Comment by kratzert** [comment]
Hi @fmclerc, thanks for reporting your finding. But I fear that I am the wrong person to notify about this, as this extension was created by @hhelgason and it would be up to him to correct his extension. Not 100% sure if he will see this issue here but I will reach out to him by mail.

**Comment by fmclerc** [comment]
Great, thank you for taking care of this!

**Comment by hhelgason** [comment]
@fmclerc, thank you for bringing this issue to our attention! @kratzert, I have updated the data on HydroShare.

**Comment by kratzert** [comment]
Perfect, thanks
