### ISSUE TITLE
[DATA CONTRIBUTION] Caravan extension Germany based on CAMELS-DE

### ISSUE THREAD

**Issue by AlexDo1** [kratzert/Caravan#35]
### Basin prefix

camelsde

### Zenodo DOI

https://doi.org/10.5281/zenodo.13320514

### Number of catchments

1887

### Location of catchments

Germany

### For which periods are streamflow records available in your dataset?

`1951-01-01` - `2020-12-31` (streamflow data has variable length)

### Please list any sources of the data you contributed.

Streamflow and water level data was obtained from thirteen German federal state agencies (German names):
- Landesanstalt für Umwelt Baden-Württemberg (LUBW)
- Bayerisches Landesamt für Umwelt (LfU-Bayern)
- Landesamt für Umwelt Brandenburg (LfU-Brandenburg)
- Hessisches Landesamt für Naturschutz, Umwelt und Geologie (HLNUG)
- Landesamt für Umwelt, Naturschutz und Geologie Mecklenburg-Vorpommern (LUNG MV)
- Niedersächsischer Landesbetrieb für Wasserwirtschaft, Küsten- und Naturschutz, Landesamt für Natur (NLWKN)
- Umwelt und Verbraucherschutz Nordrhein-Westfalen (LANUV NRW)
- Landesamt für Umwelt Rheinland-Pfalz (LUA-Rheinland Pfalz)
- Landesamt für Umwelt- und Arbeitsschutz Saarland (LUA)
- Landesamt für Umwelt, Landwirtschaft und Geologie Sachsen (LfULG)
- Landesamt für Umweltschutz Sachsen-Anhalt (LAU)
- Landesamt für Landwirtschaft, Umwelt und ländliche Räume Schleswig-Holstein (LLUR)
- Thüringer Landesamt für Umwelt, Bergbau und Naturschutz (TLUBN)

### License

CC-BY-4.0

### Additional context

Most of the catchments are also part of the already published CAMELS-DE dataset (https://doi.org/10.5281/zenodo.13837553).  
For CAMELS-DE version 1.0.0 we used meteorological forcing data that is openly available only within the borders of Germany, which is why we had to discard catchments that are partly located outside the borders of Germany. As Caravan uses globally available data sources, we could add a total of 305 catchments that are not part of the original CAMELS-DE datasets.

### Checklist

- [X] I have uploaded my dataset on Zenodo, where it is accessible under the DOI provided above.
- [X] I used a basin prefix that is not yet used by any other Caravan sub-dataset (you can check this via the [Data Contributions discussion thread](https://github.com/kratzert/Caravan/discussions/10), where all accepted Caravan contributions are listed).
- [X] Permissive License: My data is available under a license that is compatible with the Caravan CC-BY-4.0 license (the easiest way to be sure about this is if your data uses CC-BY-4.0, too).

**Comment by kratzert** [comment]
Hi @AlexDo1 

Thank you very much for contributing to Caravan. I had a look at your excellently documented extension and only have a few comments:

- There are a list of gauges with negative discharge data. Namely: 
 ['camelsde_DE412310', 'camelsde_DE811100', 'camelsde_DE811110', 'camelsde_DE811820', 'camelsde_DE912500', 'camelsde_DEA10960', 'camelsde_DEF10160', 'camelsde_DEF10250', 'camelsde_DEF11310', 'camelsde_DEF11320', 'camelsde_DEF11360', 'camelsde_DEF12170', 'camelsde_DEF12680', 'camelsde_DEF12840', 'camelsde_DEF13090', 'camelsde_DEF13130', 'camelsde_DEF13850', 'camelsde_DEF14820'] I am not sure what happened here (is this maybe an issue of the rating curve?). I looked at a few of those gauges and it did not seem to be "negative value as NaN placeholder", which some people do (e.g. -999). Do you have any explanation or is this an data (processing) error? If yes, could this be changed to NaN?

- The shapefile has an additional column that is not present in all other shapefiles (gauge_name). Not strictly necessary, but maybe for better agreement with the other shapefiles, you could remove this column and only keep gauge_id?

- The gauge_name column in the attributes_*_others.csv file seems to be only the location (i.e. village/city) but not the river. If you have information of the river name as well, do you mind changing the gauge_name column to be something like "{river name} at {location}"? Having the river name in addition to the location name often helps to better localize the gauge location in case there are issues with the lat/long values. I know this is not an ideal convention and ideally we simply would have a gauge_name and river_name column, but I messed this up with the innitial Caravan naming conventions.

**Comment by AlexDo1** [comment]
Hi @kratzert, thank you very much for your swift reply and feedback.  

1. Several people have already reported gauges with negative discharge to us in CAMELS-DE, so we have already thought about this. Most of the gauges you mentioned are located in the northern, coastal part of Germany. Negative discharges can occur here due to the influence of the tides. There are also many weirs and locks in this part of Germany, so the rivers here are heavily regulated, another possible explanation for negative discharges. Additionally, the negative discharge values are not a result of a data processing error, the German federal state agencies provided us the discharge data and claim that they quality controled the data.
We have therefore decided to keep the negative values for these gauges, as we cannot say with certainty that these are errors in the data and we even know in many cases that these negative discharges really occured.
2. Sure, I removed the `gauge_name` column from the shapefile.
3. I added the river name to the `gauge_name` of `attributes_*_others.csv` in the following format: `{river name}, {gauge_name}`. This is how the Caravan extensions Israel and Denmark also did it.

I addressed points 2 and 3 in the updated version on zenodo: https://doi.org/10.5281/zenodo.13983616 
If you want us to exclude the negative discharge values for Caravan, we can also do that.

**Comment by kratzert** [comment]
Great, thanks for the feedback and for adding the river names. I will close this PR and add the relevant info to #10 

Thanks again for contributing to Caravan and if you catch me at a conference, please say hi so that I can give you some Caravan stickers =)

**Comment by AlexDo1** [comment]
Thank you, I think we might run into each other at EGU next year :)
