### ISSUE TITLE
Earth engine library throwing errors in Caravan data contribution notebook

### ISSUE THREAD

**Issue by EmilRyd** [kratzert/Caravan#36]
I am trying to add some data to the Caravan dataset, but am running into an issue with the fetching of the static attributes from Google Earth Engine in the provided [notebook](https://github.com/kratzert/Caravan/blob/main/code/Caravan_part1_Earth_Engine.ipynb). Specifically, I am running into an issue with the ee library. In the provided notebook, the old codeline `import ee` is commented out with `from google3.geo.gestalt.client.python import ee`. This line throws an error, saying that the google3 module cannot be found (and after importing that module it says that the google.geo cannot be found).

I assume that this might be an internal google package, and so  I went ahead with trying to just use the ee package from the `import ee` line. However, then I ran into this other issue later down, in the cell under "Initializing Feature collections":
<img width="842" alt="Screenshot 2024-11-10 at 23 23 25" src="https://github.com/user-attachments/assets/f26a2a76-a553-4fed-bdd4-a8f6efbf56e7">

This error is confunding me even more, as it seems to stem from inconsistent module referencing within the ee package itself (not the Colab notebook).

It seems to me that there is some issue with the way the Earth Engine package is used in the Colab notebook, but perhaps I am doing something wrong on my end (I have never used the Earth Engine package before, so quite possible)?

**Comment by kratzert** [comment]
Thanks for reporting and wow, this seems to be in the published code for a long time. I'm looking into it, thanks for reporting,.

**Comment by kratzert** [comment]
Hmm I fear I can not reproduce your error on the feature collection. For me, with my uploaded feature collections (and after switching back to `import ee` everything worked. Maybe there is an issue with your uploaded asset of the basin shapes? If you don't mind, do you want to share your asset or at least a subset of the polygons so that I can try to reproduce it?

**Comment by kratzert** [comment]
I fixed the import statement in #37, awaiting for further feedback on the asset for the second problem you encountered.

**Comment by EmilRyd** [comment]
Thanks for fixing! Here is the asset, showing basins in Rwanda: 
[Catchment_Level2.zip](https://github.com/user-attachments/files/17700540/Catchment_Level2.zip)

The asset can also be found and downloaded [here](https://www.geoportal.rwb.rw/layers/geonode_data:geonode:Catchment_Level2#license-more-above).

I had to upload the .prj file along with the .shp, .shx, and .dbf in order to not get a projection error when upload to Google Earth Engine, but after that the upload went fine. Still, this then threw an error with the ee package later as described above.

**Comment by kratzert** [comment]
Hmm that is odd. Works for me without any issue. I just downloaded your zip file, added it as an asset (uploading all but the .sld file) and it works. I see 23 polygons. Is it maybe an permission issue that you did not give all required permissions to Earth Engine when executing the import block?

![Screenshot from 2024-11-11 12-52-10](https://github.com/user-attachments/assets/e45079e4-67ee-4b78-a384-3fb73a329382)

**Comment by EmilRyd** [comment]
Oh yeah, I tried a different Google Earth Engine account and now it works like a charm. Likely some kind of permission issue. Thanks for the help!
