### ISSUE TITLE
[DATA CONTRIBUTION] Caravan extension Denmark

### ISSUE THREAD

**Issue by JulKoch** [kratzert/Caravan#9]
### Basin prefix

camelsdk

### Zenodo DOI

https://zenodo.org/record/7396466

### Number of catchments

308

### Location of catchments

Denmark

### For which periods are streamflow records available in your dataset?

01-01-1989 until 31-12-2019

### Please list any sources of the data you contributed.

Koch, J., & Schneider, R. (2022). Long short-term memory networks enhance rainfall-runoff modelling at the national scale of Denmark. GEUS Bulletin, 49. https://doi.org/10.34194/geusb.v49.8292

### License

Creative Commons Attribution 4.0 International

### Checklist

- [X] I have uploaded my dataset on Zenodo, where it is accessible under the DOI provided above.
- [X] I used a basin prefix that is not yet used by any other Caravan sub-dataset (you can check this via the Data Contributions discussion thread (TODO link), where all accepted Caravan contributions are listed).
- [X] Permissive License: My data is available under a license that is compatible with the Caravan CC-BY-4.0 license (the easiest way to be sure about this is if your data uses CC-BY-4.0, too).

**Comment by kratzert** [comment]
Amazing, thank you so much for this very first community contribution. I will take a look at the data and then come back to you. Note: I will be on short holidays from tomorrow until Monday, so it might take a bit longer than usual.

**Comment by kratzert** [comment]
Okay, I had a look at the data and everything seems fine. I noticed that once basin is above the 2000 km2 threshold that we defined for our data, but this threshold is currently under discussion (among the authors). I'm totally fine with community extensions adding any data of any basin size they want. So congratulations again on being the first contributor. I pinned your extension in the Community Extensions Overview thread (see, #10) and will therefore close this issue.

**Comment by kratzert** [comment]
I just figured out now that the license folder in your archive is called `license` not `licenses` as in Caravan and specified in the Wiki. This results in the fact that after extracting your extension into Caravan, all folders are merged correctly but the two license/licenses folders are co-existing now side-by-side. If possible, do you mind re-uploading the data with a fixed folder name (you can update zenodo archives so you don't need to add all the authors, descriptions again, but it still creates a new DOI).

**Comment by JulKoch** [comment]
Thanks for making me aware of this. New version with corrected folder name has just been uploaded and published: https://zenodo.org/record/6762361#.YroR0OxByUk

**Comment by kratzert** [comment]
Thanks, I updated the link in the discussion thread to point to the new version!
